"""
game_research.py — Use Claude Opus with web search to research a board game.

Usage:
    python3 tools/game_research.py "Game Name" /path/to/output.md
    python3 tools/game_research.py "Game Name" /path/to/output.md --pdf /path/to/rules.pdf
"""
from __future__ import annotations

import argparse
import os
import sys

import anthropic

_KEY_FILE = os.path.expanduser("~/projects/.anthropic_api_key")
if "ANTHROPIC_API_KEY" not in os.environ and os.path.exists(_KEY_FILE):
    os.environ["ANTHROPIC_API_KEY"] = open(_KEY_FILE).read().strip()

PROMPT_TEMPLATE = """Research the board game "{game_name}" thoroughly using web search.

Please answer all of the following in a well-structured markdown document:

## Rules Summary
Describe the complete rules: setup, turn structure, valid moves, win condition, and any special mechanics. Be specific enough that a programmer could implement the game from this description alone.

## Player Count & Duration
Typical player count and game length.

## Play Experience
What do players say the experience is like? Is it tense, relaxed, cerebral, tactical, or strategic? How does it feel to play?

## Strong Points
What do reviewers and players consistently praise about this game?

## Weaknesses / Criticisms
What criticisms or weaknesses do players commonly mention?

## Strategic Depth
What are the key strategic concepts beginners miss? What separates novice from expert play?

## Implementation Notes
From a programmer's perspective: what are the trickiest rules to implement correctly? Any edge cases or common misunderstandings about the rules?

Use web search to find reviews, forum discussions (BoardGameGeek, Reddit), and rule clarifications. Cite sources inline where helpful.
"""


def research_game(game_name: str, output_path: str, pdf_path: str | None = None) -> str:
    client = anthropic.Anthropic()  # uses ANTHROPIC_API_KEY env var or ~/.anthropic/api_key

    prompt = PROMPT_TEMPLATE.format(game_name=game_name)
    if pdf_path and os.path.exists(pdf_path):
        prompt += f"\n\nNote: A PDF rulebook is available at {pdf_path} — use web search to supplement it."

    print(f"Researching '{game_name}' with Opus + web search...")

    response = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=4096,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[{"role": "user", "content": prompt}],
    )

    # Extract all text blocks from the response (may include tool use blocks)
    parts = []
    for block in response.content:
        if hasattr(block, "text"):
            parts.append(block.text)

    result = "\n\n".join(parts).strip()
    if not result:
        result = f"(No text response returned for {game_name})"

    header = f"# {game_name} — Game Research\n\n_Generated by Claude Opus with web search_\n\n"
    full = header + result

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(full)

    print(f"Saved to {output_path} ({len(full)} chars)")
    return full


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("game_name", help="Name of the board game to research")
    parser.add_argument("output_path", help="Where to save the markdown output")
    parser.add_argument("--pdf", default=None, help="Optional path to PDF rulebook")
    args = parser.parse_args()

    research_game(args.game_name, args.output_path, args.pdf)
